# Generated by Django 5.1.3 on 2024-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='provider',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
