# Generated by Django 5.1.3 on 2024-11-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_baseuser_managers_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='group',
        ),
    ]
